title:            Gymnasium Petrinum - Abi 89
tagline:          Wir kommen nur alle fünf Jahre...
description:      Alle fünf Jahre posten wir hier über unsere Abitreffen.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://abitreffen.github.io
# Owner/author information
owner:
  name:           Abi '89
  avatar:         bio-photo.jpg
  bio:            "Solid like a rock."
  email:          klaus@abitreffen.de
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        
  facebook:       
  github:         
  linkedin:       
  instagram:      
  lastfm:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Posts
    url: /posts/
  - title: Gymnasium Petrinum
    url: http://www.petrinum-brilon.de/
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Germany/Berlin
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
